pipeline {
    agent any
    tools {
        nodejs "node22"
    }
    stages {
        stage('clone repo') {
            steps {
                checkout changelog: false, poll: false, scm: scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'for-GitHub-Log-Dev', url: 'https://github.com/Oreva-J/hello-nextjs.git']])
            }
        }
        stage('install dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('build app') {
            steps {
                sh 'npm run build'
            }
        }
        stage('test app') {
            steps {
                sh 'npm run lint'
            }
        }
    }
}
